### ISSUE TITLE
Make error message more specific

### ISSUE THREAD

**Issue by gsom95** [alexander-melentyev/bizzen#2]
https://github.com/alexander-melentyev/bizzen/blob/26ed24a263c1502c12eaddf64a639ec1183029e6/internal/users/repository/postgresql/users.go#L121

https://github.com/alexander-melentyev/bizzen/blob/26ed24a263c1502c12eaddf64a639ec1183029e6/internal/users/repository/postgresql/users.go#L129
I suppose "could not create a prepared statement for **user creation**: %w" would be more specific about the problem.

https://github.com/alexander-melentyev/bizzen/blob/26ed24a263c1502c12eaddf64a639ec1183029e6/internal/users/repository/postgresql/users.go#L137

https://github.com/alexander-melentyev/bizzen/blob/26ed24a263c1502c12eaddf64a639ec1183029e6/internal/users/repository/postgresql/users.go#L145

https://github.com/alexander-melentyev/bizzen/blob/26ed24a263c1502c12eaddf64a639ec1183029e6/internal/users/repository/postgresql/users.go#L154

https://github.com/alexander-melentyev/bizzen/blob/26ed24a263c1502c12eaddf64a639ec1183029e6/internal/users/repository/postgresql/users.go#L163

https://github.com/alexander-melentyev/bizzen/blob/26ed24a263c1502c12eaddf64a639ec1183029e6/internal/users/repository/postgresql/users.go#L168

Same here.

**Comment by alexander-melentyev** [comment]
This error format for CRUD operation only, not for entity. But mb "could not execute a prepared statement for users repository create operation: %w"? What you think about this?

**Comment by gsom95** [comment]
I see but these errors are bound with CRUD operations for users repository. That's why your last version `"could not execute a prepared statement for users repository create operation: %w"` sounds much better and it should be used.

**Comment by alexander-melentyev** [comment]
Done
