### ISSUE TITLE
User UseCase checkEmail method

### ISSUE THREAD

**Issue by gsom95** [alexander-melentyev/bizzen#3]
https://github.com/alexander-melentyev/bizzen/blob/26ed24a263c1502c12eaddf64a639ec1183029e6/internal/users/usecase/users.go#L74

I think the name is not very informative: what does it check email for? Maybe it would be better if it's called something like 'emailAlreadyExists'.

https://github.com/alexander-melentyev/bizzen/blob/26ed24a263c1502c12eaddf64a639ec1183029e6/internal/users/usecase/users.go#L58
Can you explain, please, why do we need to check for email absence before updating it?

**Comment by alexander-melentyev** [comment]
I want add besides check exists in our db, check email in user service. E.g. user have email Igor@examplemail.com - if examplemail.com haven't Igor - error - "Email is not exists in examplemail.com service"

**Comment by alexander-melentyev** [comment]
Cuz if we don't check this case - user can updated email other exists users

**Comment by alexander-melentyev** [comment]
Mb call this verifyEmail?

**Comment by gsom95** [comment]
* emailExists
* isEmailUnique
* isEmailNew
* isEmailUsed
* checkEmailExistence
* checkEmailUsage
* checkEmailPresence
* emailNotUsed

**Comment by alexander-melentyev** [comment]
Take first
